sudo: required
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/sd-agent
    - vendor/cache
python:
  - "2.7"

env:
  - SKIP_CSV_CHECK_DIRS="debian/ embedded/ packaging/ vendor/"

git:
  depth: 3
branches:
  only:
    - master
    - /.*/

services:
  - docker
matrix:
  fast_finish: true

install:
  - gem install csvlint

script:
  - for d in */; do if [[ " $SKIP_CSV_CHECK_DIRS " =~ " $d " ]]; then continue; else csvlint "$d"metadata.csv; fi done
